Update osc_modif.py
jocelynj/osm pull request #4
Opened 2016-10-06 12:59 UTC by WK-GiHu

Modified: WK-GiHu osc_modif.002
##           Changed from Commandline --<Parameter> to default use unittest
##           Added TestCase #4
##           Added to Test.SetUp() - remove old tests/out/*.osc
##           Added assert os.stat("tests/polygon.poly")
##           Changed assert filecmp.cmp("tests/results/*","tests/out/*") to
##                   os.stat("tests/out/*")

2016-10-09 14:29 UTC, jocelynj commented
I don't really understand this proposed change: there are a lot of different unrelated changes. Can you make one commit per change ?
I will add some more comments on each change.

2016-10-09 14:41 UTC, jocelynj requested changes

2016-10-09 14:41 UTC, jocelynj commented on osc_modif/osc_modif.py
> +###########################################################################
This is not strictly necessary - this kind of information can be put directly on the commit message.

2016-10-09 14:41 UTC, jocelynj commented on osc_modif/osc_modif.py
> +    elif options.poly:
Hum, I'm not sure if it is correct. The previous code allowed to use an Osmosis database if no Osmbin database was present.

2016-10-09 14:41 UTC, jocelynj commented on osc_modif/osc_modif.py
> -
Why did you remove this main if ?
It is used mostly to directly generate diff with a command line, to test if everything works correctly.

The main if you added on a later commit can be replaced by launching "nosetest ./osc_modif.py"

2016-10-09 14:41 UTC, jocelynj commented on osc_modif/osc_modif.py
> +import unittest,os,shutil,filecmp,stat
Yeah, it is better to have this modules that are not used on normal code here.
It might be even better to move them in class Test below, so that they are not imported when tests are not launched.

2016-10-09 14:41 UTC, jocelynj commented on osc_modif/osc_modif.py
> +
That looks a bit complex.
Can't we just remove the file that are generated by this file, for example in the __init__() function of the class osc_modif_options ?

2016-10-09 14:41 UTC, jocelynj commented on osc_modif/osc_modif.py
> -            os.makedirs("tests/out")
Don't we still need this code to create tests/out if it doesn't exist ?

2016-10-09 14:41 UTC, jocelynj commented on osc_modif/osc_modif.py
> +        #return os.stat(opt.dest)
Please keep the original code using filecmp. You can easily make the check passing by copying tests/out/* files to tests/result/

2016-10-09 14:41 UTC, jocelynj commented on osc_modif/osc_modif.py
> +        del opt
Note that without comparing outputs, this code doesn't really check if the outputs are correct. It only checks that python code is not crashing.
Or do you intend to add more checks later ?

2016-10-13 14:18 UTC, WK-GiHu commented on osc_modif/osc_modif.py
> +###########################################################################
Old habit, should be removed before 'upload'.

2016-10-13 14:22 UTC, WK-GiHu commented on osc_modif/osc_modif.py
> +import unittest,os,shutil,filecmp,stat
Moving them in class Test does not work. For conditional import you need a 'if ... :' statement.
I will keep this in mind.

2016-10-13 14:49 UTC, WK-GiHu commented on osc_modif/osc_modif.py
> +
Copied from 'rmTree' and overlooked that 'os.remove(path)'  will do it.
Will change it to 'os.remove(path)'.
It has to do with Test 'setup', therefore I find 'Test.setUp()' OK.
osc_modif_options.__init__() is not possible because its called bevor every TestCase #.
The call to os.remove("tests/out/*") is to be called only once and must executed at the beginning of 'unittest.main.test().

2016-10-13 14:54 UTC, WK-GiHu commented on osc_modif/osc_modif.py
> -            os.makedirs("tests/out")
Version conflict! You modified osc_modif.py 8 day ago, didn't notice that. 
My local version does not have the lines 114-115. I will add these lines and combine with the above call to os.remove("tests/out/*")

2016-10-13 15:10 UTC, WK-GiHu commented on osc_modif/osc_modif.py
> +        #return os.stat(opt.dest)
As for now i see these check useless.
Read following, shows how 'filecmp.cmp(...)' will work. Three data will be compared (mode,size,mtime), 'mtime' allways changes, assert will allways fail. 
def filecmp.cmp(f1, f2, shallow=1)
    Compare two files.
    Arguments:
    f1 -- First file name
    f2 -- Second file name
    shallow -- Just check stat signature (do not read the files).
               defaults to 1.
tests/out/001.poly.osc		(mode=32768,size=5786,mtime=1475781911.45[Thu Oct  6 21:25:11 2016])
tests/results/001.poly.osc	(mode=32768,size=5786,mtime=1475500907.32[Mon Oct  3 15:21:47 2016])

We should ask the question: What should here be checked?

2016-10-13 15:15 UTC, WK-GiHu commented on osc_modif/osc_modif.py
> +        del opt
Yes, in conjunction with 'os.remove("tests/out/*")' it only checks that a new file was created.
The same as above: What should here be checked?

2016-10-18 19:35 UTC, WK-GiHu commented on osc_modif/osc_modif.py
> +    elif options.poly:
`unittest.main().test()` does pass` options.osmbin_path = "tmp-osmbin/"` and never throws `except IOError:`. As for now `update.py `will **not** work, have to be changed to pass `options.osmbin_path = `as well.

2016-10-18 19:49 UTC, WK-GiHu commented on osc_modif/osc_modif.py
> -
As unittest.main().test() does not use it.
To test this i need real command line paramters from you.
I suggest to split osc_modif.py into two files.
1. **osc_modif.py** with this removed `main if`
2. **modules/updateLib.py with** `def osc_modif`, even better `class osc_modif()` and `class Test()`

2016-10-18 20:10 UTC, WK-GiHu commented
We have to make a decision.

There are 3 different modes, parameters are given over to `def osc_modif(...)`:
a) **update.py**: Not passing `options.osmbin_path`; controlled by `def osc_modif(...)`
b) **unittest.main.test**: Passing `options.osmbin_path`; controlled by the caller
c) **command line**: Not passing `options.osmbin_path`, pass additional `config`; controlled by caller and `def osc_modif(...)`

Will we stay on this?
I prefer **b)**, all controlled by the caller.

2016-10-18 21:18 UTC, jocelynj commented on osc_modif/osc_modif.py
> +        #return os.stat(opt.dest)
Yes, you're right that filecmp.cmp is not the correct function to use.
What we want to check is that the test generate the same output than the committed file on git.

2016-10-18 21:22 UTC, jocelynj commented
I agree that it makes sense to set osmbin_path in the caller. Can you add it to update.py and main as necessary ?

About all the changes: can you try to make several commits, one per change ? It will be a lot easier to review the changes, and I will be able to cherry-pick the changes that I can accept immediately.

2016-10-23 13:31 UTC, closed without merging